on:
  push:
    tags:
      - 'cbmc-*'

name: Create Release

jobs:
  perform-release:
    name: Perform Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        uses: actions/create-release@v1
        env:
          CBMC_TAG: ${{ github.ref }}
        with:
          tag_name: $CBMC_TAG
          release_name: $CBMC_TAG
          body: |
            **Installation instructions**:
              * For Windows, execute the installer `$CBMC_TAG-win64.msi`.
              * For Linux, install the `.deb` package with 
                `sudo apt install $CBMC_TAG-Linux.deb` on Debian-like systems
              * For macOS, install with `brew install cbmc` or upgrade with
                `brew upgrade cbmc`
          draft: false
          prerelease: false
