on:
  push:
    tags:
      - 'cbmc-*'

name: Create Release

jobs:
  get-version-information:
    name: Get Version Information
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.split.outputs._2 }}
    steps:
      - uses: jungwinter/split@v1
        id: split
        with:
          msg: ${{ github.ref }}
          seperator: '/'
  perform-release:
    name: Perform Release
    runs-on: ubuntu-20.04
    needs: get-version-information
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.FOTIS_GITHUB_TOKEN }}
          CBMC_TAG: ${{ needs.get-version-information.outputs.version }}
        with:
          tag_name: ${{ env.CBMC_TAG }}
          release_name: ${{ env.CBMC_TAG }}
          body: |
            **Installation instructions**:
              * For Windows, execute the installer `${{ tag_name }}-win64.msi`.
              * For Linux, install the `.deb` package with 
                `sudo apt install $CBMC_TAG-Linux.deb` on Debian-like systems
              * For macOS, install with `brew install cbmc` or upgrade with
                `brew upgrade cbmc`
          draft: false
          prerelease: false
